#!/usr/bin/env python3

import csv
import json
import sys

csv.register_dialect('strip', skipinitialspace=True)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        reader = csv.DictReader(open(sys.argv[1]),dialect='strip')
    elif sys.stdin:
        reader = csv.DictReader(sys.stdin,dialect='strip')

    reader = (dict((k, v.strip()) for k, v in row.items() if v) for row in reader)

    output = json.dumps([r for r in reader], sort_keys=False,
                        ensure_ascii=True, indent=2, separators=(',', ': '))
    print(output)

